---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all-github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all-pre-commit-hooks:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "lockfile-only"
    groups:
      all-deps:
        patterns:
          - "*"
    cooldown:
      default-days: 7
