name: style

permissions:
   contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  UV_FROZEN: true

jobs:
  fmu-ensemble:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: 📖 Checkout commit locally
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 📖 Checkout tags
        # This seems necessary for setuptools_scm to be able to infer
        # the correct version.
        run: git fetch --unshallow --tags

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          prune-cache: false
          python-version: ${{ matrix.python-version }}

      - name: 📦 Install fmu-ensemble with style dependencies
        run: |
          uv sync --extra=style

      - name: 🕵️ Check code style
        env:
          SKIP: no-commit-to-branch
        run: |
          uv run pre-commit run --all-files
